/* TABLE */
CREATE TABLE "user" (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    password text NOT NULL,
    -- refresh_token really should be NOT NULL but the seed data doesn't have them
    refresh_token text UNIQUE
);

COMMENT ON TABLE "user" IS 'Someone with an account on the site, who uses it to make purchases';

COMMENT ON COLUMN "user"."password" IS 'A bcrypt-hashed version of the user password, compared against securely in the JWT Auth API handler for sign-in';


/* FOREIGN KEYS */
/* TRIGGERS */
CREATE TRIGGER set_user_updated_at
    BEFORE UPDATE ON public.user
    FOR EACH ROW
    EXECUTE FUNCTION public.set_current_timestamp_updated_at ();
