/* TABLE */
CREATE TABLE "site_admin" (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    password text NOT NULL,
    refresh_token text UNIQUE
);

COMMENT ON TABLE "site_admin" IS 'Someone administrative capabilities on the site';

COMMENT ON COLUMN "site_admin"."password" IS 'A bcrypt-hashed version of the admin password, compared against securely in the JWT Auth API handler for sign-in';


/* FOREIGN KEYS */
/* TRIGGERS */
CREATE TRIGGER set_site_admin_updated_at
    BEFORE UPDATE ON public.site_admin
    FOR EACH ROW
    EXECUTE FUNCTION public.set_current_timestamp_updated_at ();
