/* TABLE */
CREATE TABLE "product_review" (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    user_id int NOT NULL,
    product_id int NOT NULL,
    rating int NOT NULL CHECK (rating >= 1 AND rating <= 5),
    -- 5,000 characters = 800 words or 1.5 pages single-spaced (based on 6-char word avg)
    comment text NOT NULL CHECK (char_length(comment) <= 5000),
    -- Only allow each person to leave one review per product they've purchased
    CONSTRAINT one_review_per_person_and_product UNIQUE (user_id, product_id)
);

COMMENT ON TABLE "product_review" IS 'A review for a product which a customer has purchased before';


/* FOREIGN KEYS */
ALTER TABLE ONLY public.product_review
    ADD CONSTRAINT user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user (id);

ALTER TABLE ONLY public.product_review
    ADD CONSTRAINT product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product (id);


/* TRIGGERS */
CREATE TRIGGER set_product_review_updated_at
    BEFORE UPDATE ON public.product_review
    FOR EACH ROW
    EXECUTE FUNCTION public.set_current_timestamp_updated_at ();
