/* TABLE */
CREATE TABLE product (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    name text NOT NULL,
    -- Do we want description to be mandatory?
    description text,
    category_display_name text NOT NULL,
    brand text,
    price numeric NOT NULL,
    -- TODO: Make "product_image_url" table and one-to-many relationship from product -> product_image_url
    -- The Kaggle data just came with it in this format so we can hackily (ab)use JSONB for shitty relationships
    image_urls jsonb
);


/* FOREIGN KEYS */
ALTER TABLE ONLY public.product
    ADD CONSTRAINT category_display_name_fk FOREIGN KEY (category_display_name) REFERENCES public.product_category_enum (display_name);


/* TRIGGERS */
CREATE TRIGGER set_product_updated_at
    BEFORE UPDATE ON public.product
    FOR EACH ROW
    EXECUTE FUNCTION public.set_current_timestamp_updated_at ();

