insert into public.address (user_id, city, state, zipcode, address_line_one) values (4, 'Springfield', 'Massachusetts', '01129', '119 Victoria Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (5, 'Indianapolis', 'Indiana', '46216', '06 Holy Cross Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (6, 'Athens', 'Georgia', '30610', '1287 Clyde Gallagher Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (7, 'Orlando', 'Florida', '32813', '02572 Forest Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (8, 'Reading', 'Pennsylvania', '19605', '83625 Dawn Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (9, 'Daytona Beach', 'Florida', '32128', '9202 Carpenter Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (10, 'El Paso', 'Texas', '88579', '509 Grayhawk Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (11, 'Tacoma', 'Washington', '98411', '5 Troy Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (12, 'New Castle', 'Pennsylvania', '16107', '7 Bay Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (13, 'El Paso', 'Texas', '79955', '5763 Mendota Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (14, 'Anaheim', 'California', '92825', '7 Mayer Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (15, 'Dallas', 'Texas', '75372', '31319 Maple Wood Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (16, 'Anchorage', 'Alaska', '99599', '111 Bashford Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (17, 'Tulsa', 'Oklahoma', '74184', '77416 Birchwood Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (18, 'Oklahoma City', 'Oklahoma', '73109', '74037 Comanche Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (19, 'Fullerton', 'California', '92640', '36599 Pennsylvania Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (20, 'San Jose', 'California', '95113', '1 Hoffman Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (21, 'Albuquerque', 'New Mexico', '87110', '950 Thompson Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (22, 'Oakland', 'California', '94611', '2933 Bellgrove Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (23, 'San Diego', 'California', '92153', '8962 Katie Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (24, 'Amarillo', 'Texas', '79105', '2 Gina Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (25, 'Lansing', 'Michigan', '48912', '60 Jenna Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (26, 'Sacramento', 'California', '95823', '2196 Corscot Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (27, 'Elizabeth', 'New Jersey', '07208', '1 Portage Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (28, 'Norfolk', 'Virginia', '23514', '9 Knutson Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (29, 'Indianapolis', 'Indiana', '46266', '2394 Talisman Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (30, 'Tucson', 'Arizona', '85732', '139 Sherman Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (31, 'El Paso', 'Texas', '79989', '7 Grover Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (32, 'Los Angeles', 'California', '90005', '1620 Ilene Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (33, 'Huntington', 'West Virginia', '25770', '93 Macpherson Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (34, 'Kansas City', 'Kansas', '66160', '02 Green Ridge Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (35, 'Cincinnati', 'Ohio', '45243', '6 Cascade Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (36, 'Fresno', 'California', '93721', '55 New Castle Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (37, 'Tulsa', 'Oklahoma', '74156', '2483 Upham Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (38, 'Miami', 'Florida', '33261', '2 Jackson Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (39, 'Houston', 'Texas', '77075', '89 Service Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (40, 'Lexington', 'Kentucky', '40586', '61159 Onsgard Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (41, 'Saint Augustine', 'Florida', '32092', '69 Magdeline Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (42, 'San Angelo', 'Texas', '76905', '1043 Novick Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (43, 'Norfolk', 'Virginia', '23520', '62190 Jana Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (44, 'Canton', 'Ohio', '44710', '0 Eggendart Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (45, 'Helena', 'Montana', '59623', '2 Thackeray Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (46, 'Montgomery', 'Alabama', '36177', '012 Dixon Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (47, 'Troy', 'Michigan', '48098', '4 Bashford Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (48, 'Amarillo', 'Texas', '79105', '4176 Clyde Gallagher Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (49, 'Stamford', 'Connecticut', '06922', '5975 Armistice Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (50, 'Rochester', 'New York', '14652', '811 Tony Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (51, 'Houston', 'Texas', '77095', '737 Steensland Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (52, 'Alexandria', 'Virginia', '22333', '4777 Lerdahl Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (53, 'Knoxville', 'Tennessee', '37914', '01294 Warbler Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (54, 'Valdosta', 'Georgia', '31605', '1 Ramsey Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (55, 'Wilmington', 'North Carolina', '28410', '48 Main Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (56, 'Nashville', 'Tennessee', '37228', '076 Buhler Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (57, 'Pittsburgh', 'Pennsylvania', '15279', '5291 Haas Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (58, 'Birmingham', 'Alabama', '35205', '94012 Bellgrove Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (59, 'San Jose', 'California', '95160', '86685 Rieder Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (60, 'Dayton', 'Ohio', '45440', '527 Hintze Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (61, 'Saint Louis', 'Missouri', '63196', '1 Kensington Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (62, 'Boston', 'Massachusetts', '02208', '45321 Thackeray Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (63, 'Denver', 'Colorado', '80279', '54 Sloan Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (64, 'Albuquerque', 'New Mexico', '87190', '1 Thompson Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (65, 'Clearwater', 'Florida', '34629', '00356 Sugar Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (66, 'Knoxville', 'Tennessee', '37939', '69 Ryan Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (67, 'Shreveport', 'Louisiana', '71166', '10473 Brown Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (68, 'Houston', 'Texas', '77260', '44 Warrior Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (69, 'Albuquerque', 'New Mexico', '87195', '55415 Waywood Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (70, 'Lansing', 'Michigan', '48930', '9830 Sycamore Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (71, 'Waltham', 'Massachusetts', '02453', '24648 Lakewood Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (72, 'Lexington', 'Kentucky', '40505', '30550 Macpherson Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (73, 'Phoenix', 'Arizona', '85053', '36184 Eggendart Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (74, 'Gastonia', 'North Carolina', '28055', '5839 Dapin Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (75, 'Baton Rouge', 'Louisiana', '70883', '1646 Merry Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (76, 'Newark', 'Delaware', '19725', '26795 Swallow Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (77, 'Ogden', 'Utah', '84409', '3329 Jana Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (78, 'Raleigh', 'North Carolina', '27610', '01950 Graedel Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (79, 'San Antonio', 'Texas', '78260', '08 Elmside Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (80, 'New York City', 'New York', '10170', '0 Swallow Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (81, 'San Antonio', 'Texas', '78240', '4991 Menomonie Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (82, 'Austin', 'Texas', '78721', '854 Waywood Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (83, 'San Angelo', 'Texas', '76905', '7 Lindbergh Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (84, 'Los Angeles', 'California', '90071', '99 Welch Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (85, 'Richmond', 'Virginia', '23228', '7 Commercial Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (86, 'Oklahoma City', 'Oklahoma', '73157', '1090 Hoepker Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (87, 'Columbia', 'South Carolina', '29208', '894 Hoard Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (88, 'Roanoke', 'Virginia', '24048', '1584 Rowland Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (89, 'Lexington', 'Kentucky', '40510', '0983 Elmside Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (90, 'Portland', 'Oregon', '97232', '264 Eggendart Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (91, 'Houston', 'Texas', '77070', '54 Debs Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (92, 'Corpus Christi', 'Texas', '78410', '65 5th Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (93, 'Arlington', 'Virginia', '22244', '7 Arrowood Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (94, 'Anchorage', 'Alaska', '99599', '2 Pearson Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (95, 'Canton', 'Ohio', '44760', '5 Lawn Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (96, 'Arlington', 'Virginia', '22234', '0607 Rockefeller Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (97, 'Saginaw', 'Michigan', '48604', '68566 Mallard Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (98, 'Detroit', 'Michigan', '48242', '7513 Prairieview Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (99, 'Tampa', 'Florida', '33686', '7928 Golf Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (100, 'San Francisco', 'California', '94154', '69 Burrows Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (101, 'Saginaw', 'Michigan', '48604', '8 Mesta Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (102, 'Akron', 'Ohio', '44305', '0316 Nova Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (103, 'Fresno', 'California', '93715', '8 Onsgard Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (104, 'Boston', 'Massachusetts', '02298', '7134 Lawn Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (105, 'Frederick', 'Maryland', '21705', '6471 Muir Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (106, 'Salt Lake City', 'Utah', '84115', '3384 Carberry Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (107, 'Washington', 'District of Columbia', '20057', '013 Thompson Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (108, 'Cleveland', 'Ohio', '44191', '17 Bowman Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (109, 'Saint Cloud', 'Minnesota', '56372', '1 Del Sol Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (110, 'El Paso', 'Texas', '79994', '1919 Ludington Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (111, 'Allentown', 'Pennsylvania', '18105', '17647 Shoshone Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (112, 'Bronx', 'New York', '10459', '0 Namekagon Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (113, 'Corona', 'California', '92878', '11 Monterey Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (114, 'Pittsburgh', 'Pennsylvania', '15286', '206 Novick Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (115, 'Washington', 'District of Columbia', '20099', '73 Anzinger Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (116, 'Jamaica', 'New York', '11436', '66 Meadow Vale Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (117, 'Washington', 'District of Columbia', '20456', '4675 Menomonie Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (118, 'Cincinnati', 'Ohio', '45203', '9 La Follette Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (119, 'Jacksonville', 'Florida', '32215', '996 South Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (120, 'Greenville', 'South Carolina', '29605', '0106 Myrtle Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (121, 'Shawnee Mission', 'Kansas', '66225', '0083 Gerald Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (122, 'Washington', 'District of Columbia', '20041', '72954 Loftsgordon Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (123, 'San Antonio', 'Texas', '78260', '45 Elmside Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (124, 'Bronx', 'New York', '10454', '8867 Namekagon Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (125, 'Corona', 'California', '92878', '17 Vidon Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (126, 'Moreno Valley', 'California', '92555', '933 Clyde Gallagher Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (127, 'Memphis', 'Tennessee', '38114', '3660 Colorado Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (128, 'Bakersfield', 'California', '93381', '1557 Granby Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (129, 'Gulfport', 'Mississippi', '39505', '357 Spaight Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (130, 'Evansville', 'Indiana', '47737', '366 Manley Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (131, 'Amarillo', 'Texas', '79159', '565 Michigan Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (132, 'Richmond', 'Virginia', '23220', '5 Hovde Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (133, 'Las Cruces', 'New Mexico', '88006', '680 Graceland Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (134, 'Albuquerque', 'New Mexico', '87110', '26 Shelley Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (135, 'Henderson', 'Nevada', '89012', '4 Sunnyside Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (136, 'Saint Paul', 'Minnesota', '55123', '01 3rd Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (137, 'Huntsville', 'Texas', '77343', '04 Trailsway Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (138, 'Saint Paul', 'Minnesota', '55172', '454 Bayside Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (139, 'El Paso', 'Texas', '79940', '91257 Comanche Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (140, 'Corpus Christi', 'Texas', '78465', '8884 Lukken Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (141, 'Kalamazoo', 'Michigan', '49006', '05191 Orin Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (142, 'Kansas City', 'Missouri', '64125', '68977 Porter Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (143, 'Kansas City', 'Missouri', '64114', '5367 Fieldstone Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (144, 'Chicago', 'Illinois', '60663', '6997 Loomis Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (145, 'Tacoma', 'Washington', '98481', '8688 Dryden Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (146, 'Fort Lauderdale', 'Florida', '33320', '7 Warrior Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (147, 'San Diego', 'California', '92115', '53367 Darwin Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (148, 'Washington', 'District of Columbia', '20414', '1 Fairfield Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (149, 'Metairie', 'Louisiana', '70005', '1 Maryland Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (150, 'New York City', 'New York', '10155', '53 Johnson Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (151, 'Midland', 'Michigan', '48670', '945 Gateway Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (152, 'Lakeland', 'Florida', '33811', '3554 Pennsylvania Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (153, 'Fort Lauderdale', 'Florida', '33345', '2458 Forest Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (154, 'Raleigh', 'North Carolina', '27635', '26 Huxley Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (155, 'Washington', 'District of Columbia', '20310', '03 Sommers Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (156, 'Richmond', 'Virginia', '23277', '24775 Mallard Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (157, 'Littleton', 'Colorado', '80126', '09132 Myrtle Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (158, 'Los Angeles', 'California', '90071', '625 Warbler Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (159, 'Washington', 'District of Columbia', '20503', '8 Green Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (160, 'Palatine', 'Illinois', '60078', '349 5th Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (161, 'Philadelphia', 'Pennsylvania', '19184', '01905 Amoth Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (162, 'Bradenton', 'Florida', '34205', '5200 John Wall Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (163, 'Carson City', 'Nevada', '89714', '2323 Florence Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (164, 'Irving', 'Texas', '75037', '466 Charing Cross Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (165, 'Waterbury', 'Connecticut', '06726', '993 Anniversary Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (166, 'Richmond', 'Virginia', '23272', '90896 Stone Corner Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (167, 'Atlanta', 'Georgia', '30375', '2 Armistice Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (168, 'Mesquite', 'Texas', '75185', '0 Weeping Birch Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (169, 'Los Angeles', 'California', '90060', '916 Butterfield Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (170, 'Seattle', 'Washington', '98104', '82201 Clarendon Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (171, 'Detroit', 'Michigan', '48275', '62567 Walton Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (172, 'Arlington', 'Texas', '76004', '897 Anniversary Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (173, 'Austin', 'Texas', '78737', '309 Fisk Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (174, 'Austin', 'Texas', '78744', '1 Burning Wood Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (175, 'Miami', 'Florida', '33233', '30120 Truax Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (176, 'Sacramento', 'California', '94263', '47485 Sauthoff Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (177, 'Denver', 'Colorado', '80209', '704 Morrow Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (178, 'Cumming', 'Georgia', '30130', '61 Homewood Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (179, 'Watertown', 'Massachusetts', '02472', '443 Bonner Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (180, 'Houston', 'Texas', '77035', '454 Sycamore Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (181, 'Monticello', 'Minnesota', '55590', '3 Carpenter Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (182, 'Colorado Springs', 'Colorado', '80945', '8 Red Cloud Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (183, 'Los Angeles', 'California', '90101', '750 Loftsgordon Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (184, 'Escondido', 'California', '92030', '93634 Farwell Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (185, 'Racine', 'Wisconsin', '53405', '45 Golf View Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (186, 'Oakland', 'California', '94616', '29 Northview Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (187, 'Washington', 'District of Columbia', '20205', '2 Sommers Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (188, 'Las Vegas', 'Nevada', '89120', '31088 Warbler Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (189, 'Kansas City', 'Missouri', '64149', '413 Nevada Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (190, 'Fort Worth', 'Texas', '76115', '20 Colorado Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (191, 'Fort Worth', 'Texas', '76178', '35 Duke Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (192, 'Southfield', 'Michigan', '48076', '694 Monica Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (193, 'Tampa', 'Florida', '33686', '5 Katie Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (194, 'Santa Fe', 'New Mexico', '87505', '3 Porter Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (195, 'Saint Petersburg', 'Florida', '33705', '4 Autumn Leaf Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (196, 'Fort Smith', 'Arkansas', '72916', '6489 Loomis Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (197, 'Galveston', 'Texas', '77554', '80 Hanson Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (198, 'Oklahoma City', 'Oklahoma', '73135', '9 Mayer Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (199, 'San Antonio', 'Texas', '78220', '7367 Merry Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (200, 'Elmira', 'New York', '14905', '066 Anzinger Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (201, 'West Hartford', 'Connecticut', '06127', '8386 Dawn Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (202, 'Davenport', 'Iowa', '52804', '8 Melrose Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (203, 'Washington', 'District of Columbia', '20530', '336 Rockefeller Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (204, 'Garland', 'Texas', '75044', '52 Talmadge Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (205, 'Springfield', 'Illinois', '62756', '9785 Birchwood Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (206, 'Tucson', 'Arizona', '85754', '61256 Meadow Valley Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (207, 'San Jose', 'California', '95113', '1 Magdeline Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (208, 'El Paso', 'Texas', '79950', '8 Gateway Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (209, 'Dallas', 'Texas', '75387', '125 Muir Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (210, 'Clearwater', 'Florida', '34620', '1 Thompson Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (211, 'Staten Island', 'New York', '10310', '44953 Clemons Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (212, 'Simi Valley', 'California', '93094', '941 Sage Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (213, 'Atlanta', 'Georgia', '30358', '831 Ohio Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (214, 'Washington', 'District of Columbia', '20310', '49614 Sherman Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (215, 'Jackson', 'Mississippi', '39204', '22747 Fremont Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (216, 'Birmingham', 'Alabama', '35210', '871 Russell Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (217, 'Irving', 'Texas', '75062', '6 Melvin Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (218, 'Charleston', 'West Virginia', '25313', '6836 Clyde Gallagher Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (219, 'Metairie', 'Louisiana', '70033', '6 Eagle Crest Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (220, 'Fort Lauderdale', 'Florida', '33345', '07240 Commercial Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (221, 'Lexington', 'Kentucky', '40586', '4 Mcguire Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (222, 'Portland', 'Oregon', '97216', '8 Amoth Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (223, 'Bridgeport', 'Connecticut', '06606', '44 Kedzie Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (224, 'New York City', 'New York', '10079', '16 Novick Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (225, 'Orlando', 'Florida', '32819', '920 Alpine Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (226, 'Bozeman', 'Montana', '59771', '1470 Vermont Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (227, 'New Orleans', 'Louisiana', '70124', '97640 Ruskin Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (228, 'Boston', 'Massachusetts', '02283', '5092 Union Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (229, 'Colorado Springs', 'Colorado', '80940', '563 Dunning Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (230, 'Fort Wayne', 'Indiana', '46852', '82 Elka Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (231, 'Baltimore', 'Maryland', '21290', '8018 Ludington Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (232, 'Birmingham', 'Alabama', '35236', '8 Grim Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (233, 'New York City', 'New York', '10105', '1856 Anderson Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (234, 'Seattle', 'Washington', '98158', '89 Merry Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (235, 'Chicago', 'Illinois', '60636', '5539 Starling Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (236, 'Peoria', 'Illinois', '61656', '4373 Arapahoe Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (237, 'Visalia', 'California', '93291', '295 Stephen Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (238, 'Pensacola', 'Florida', '32575', '15 Quincy Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (239, 'El Paso', 'Texas', '79989', '83 Southridge Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (240, 'Detroit', 'Michigan', '48211', '729 Lakewood Gardens Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (241, 'El Paso', 'Texas', '79968', '97598 Continental Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (242, 'Silver Spring', 'Maryland', '20910', '66055 4th Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (243, 'Boston', 'Massachusetts', '02109', '7 Lunder Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (244, 'Fort Worth', 'Texas', '76162', '14 Bunker Hill Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (245, 'Atlanta', 'Georgia', '30323', '06215 Hoepker Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (246, 'Shreveport', 'Louisiana', '71166', '660 Logan Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (247, 'Birmingham', 'Alabama', '35220', '66 Browning Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (248, 'Springfield', 'Missouri', '65898', '2 Marquette Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (249, 'El Paso', 'Texas', '88519', '2 Jay Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (250, 'Wilmington', 'North Carolina', '28410', '5263 Hoepker Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (251, 'Pensacola', 'Florida', '32505', '44544 Browning Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (252, 'Escondido', 'California', '92030', '86933 Loomis Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (253, 'Nashville', 'Tennessee', '37235', '8539 Caliangt Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (254, 'El Paso', 'Texas', '79955', '8 Luster Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (255, 'Jamaica', 'New York', '11431', '627 Stephen Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (256, 'New Orleans', 'Louisiana', '70142', '7 Hauk Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (257, 'Bronx', 'New York', '10454', '4 Ramsey Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (258, 'Lincoln', 'Nebraska', '68505', '6 Morrow Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (259, 'Tucson', 'Arizona', '85710', '6790 Shopko Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (260, 'Washington', 'District of Columbia', '20067', '5879 Bartillon Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (261, 'Charleston', 'West Virginia', '25331', '8897 Blaine Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (262, 'Fresno', 'California', '93715', '04 6th Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (263, 'Elmira', 'New York', '14905', '383 Roth Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (264, 'Saint Louis', 'Missouri', '63167', '12642 David Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (265, 'Las Vegas', 'Nevada', '89110', '9371 Reinke Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (266, 'Madison', 'Wisconsin', '53710', '801 Northview Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (267, 'Los Angeles', 'California', '90025', '1 Macpherson Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (268, 'Houston', 'Texas', '77281', '48 Prentice Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (269, 'Columbia', 'South Carolina', '29208', '789 Goodland Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (270, 'Santa Barbara', 'California', '93111', '062 Lerdahl Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (271, 'Greensboro', 'North Carolina', '27499', '61 Beilfuss Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (272, 'Fullerton', 'California', '92835', '3 Forest Run Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (273, 'Albany', 'New York', '12262', '317 Forest Run Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (274, 'Anchorage', 'Alaska', '99522', '5 Esch Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (275, 'Salt Lake City', 'Utah', '84199', '59 Glacier Hill Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (276, 'Jackson', 'Mississippi', '39282', '2 Golf View Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (277, 'Austin', 'Texas', '78710', '16780 Rockefeller Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (278, 'Gainesville', 'Florida', '32605', '16 Homewood Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (279, 'Washington', 'District of Columbia', '20425', '81271 Karstens Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (280, 'Saint Louis', 'Missouri', '63110', '99256 Bobwhite Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (281, 'Boston', 'Massachusetts', '02216', '6 Fairfield Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (282, 'Minneapolis', 'Minnesota', '55446', '2156 Truax Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (283, 'Indianapolis', 'Indiana', '46231', '6034 Thompson Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (284, 'Tucson', 'Arizona', '85710', '3 Sachs Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (285, 'Providence', 'Rhode Island', '02905', '47009 Maryland Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (286, 'Omaha', 'Nebraska', '68134', '1 Nova Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (287, 'Visalia', 'California', '93291', '706 Moulton Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (288, 'Danbury', 'Connecticut', '06816', '0806 Park Meadow Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (289, 'Minneapolis', 'Minnesota', '55428', '48 Kennedy Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (290, 'Lexington', 'Kentucky', '40515', '431 Browning Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (291, 'Lincoln', 'Nebraska', '68531', '898 Longview Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (292, 'Mobile', 'Alabama', '36616', '800 Hazelcrest Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (293, 'Chicago', 'Illinois', '60609', '0 Crownhardt Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (294, 'New York City', 'New York', '10105', '0 Rieder Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (295, 'Orlando', 'Florida', '32835', '1 Mallard Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (296, 'San Francisco', 'California', '94147', '251 Acker Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (297, 'Erie', 'Pennsylvania', '16565', '985 Dryden Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (298, 'Cleveland', 'Ohio', '44125', '74 Fuller Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (299, 'Oakland', 'California', '94605', '450 Shelley Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (300, 'Phoenix', 'Arizona', '85015', '89 Barnett Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (301, 'Macon', 'Georgia', '31296', '0 Bayside Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (302, 'Pinellas Park', 'Florida', '34665', '53 Duke Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (303, 'Jacksonville', 'Florida', '32204', '9666 Riverside Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (304, 'Fredericksburg', 'Virginia', '22405', '301 Cody Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (305, 'El Paso', 'Texas', '79940', '2218 Washington Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (306, 'New York City', 'New York', '10150', '974 Aberg Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (307, 'San Jose', 'California', '95160', '08109 Mayer Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (308, 'Arlington', 'Virginia', '22212', '0985 Clarendon Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (309, 'Baton Rouge', 'Louisiana', '70836', '8 Buell Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (310, 'South Bend', 'Indiana', '46614', '965 Sullivan Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (311, 'Austin', 'Texas', '78769', '48226 Straubel Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (312, 'Kansas City', 'Missouri', '64190', '71300 Oak Valley Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (313, 'Greensboro', 'North Carolina', '27404', '19687 Maywood Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (314, 'Jacksonville', 'Florida', '32204', '9 Rusk Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (315, 'Evansville', 'Indiana', '47719', '29 Donald Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (316, 'Lincoln', 'Nebraska', '68510', '88 Talisman Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (317, 'Los Angeles', 'California', '90035', '1036 Chive Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (318, 'Temple', 'Texas', '76505', '8730 Aberg Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (319, 'Waterbury', 'Connecticut', '06726', '3 2nd Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (320, 'Atlanta', 'Georgia', '30392', '5 Namekagon Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (321, 'Terre Haute', 'Indiana', '47812', '31 Ilene Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (322, 'Pensacola', 'Florida', '32505', '74910 Bowman Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (323, 'Los Angeles', 'California', '90087', '527 Beilfuss Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (324, 'San Francisco', 'California', '94121', '19 Debs Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (325, 'Saint Louis', 'Missouri', '63116', '2 Mallard Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (326, 'Aurora', 'Colorado', '80015', '80010 Homewood Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (327, 'Seattle', 'Washington', '98140', '30 Troy Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (328, 'Kansas City', 'Kansas', '66160', '725 Brown Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (329, 'San Diego', 'California', '92153', '32 Green Ridge Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (330, 'Springfield', 'Illinois', '62711', '53161 Tony Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (331, 'Colorado Springs', 'Colorado', '80925', '14636 Forster Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (332, 'Atlanta', 'Georgia', '30386', '90746 Lindbergh Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (333, 'Riverside', 'California', '92519', '58 Prairieview Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (334, 'Des Moines', 'Iowa', '50981', '24 Sugar Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (335, 'Durham', 'North Carolina', '27717', '670 American Ash Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (336, 'Topeka', 'Kansas', '66617', '4407 Hollow Ridge Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (337, 'Cincinnati', 'Ohio', '45238', '60 Fisk Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (338, 'Evansville', 'Indiana', '47747', '10893 Cascade Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (339, 'Los Angeles', 'California', '90076', '013 Gerald Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (340, 'Houston', 'Texas', '77288', '131 Pennsylvania Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (341, 'Jamaica', 'New York', '11407', '084 Kensington Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (342, 'Seattle', 'Washington', '98121', '6117 Center Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (343, 'West Hartford', 'Connecticut', '06127', '4 Red Cloud Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (344, 'Sioux Falls', 'South Dakota', '57105', '5 Mcbride Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (345, 'Buffalo', 'New York', '14210', '148 Mayer Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (346, 'Springfield', 'Missouri', '65805', '98 Westend Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (347, 'New York City', 'New York', '10270', '9 Spohn Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (348, 'Arlington', 'Virginia', '22244', '3786 Farragut Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (349, 'New Orleans', 'Louisiana', '70174', '8674 Kinsman Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (350, 'Buffalo', 'New York', '14210', '951 Washington Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (351, 'Baton Rouge', 'Louisiana', '70820', '07 Manufacturers Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (352, 'Nashville', 'Tennessee', '37210', '518 Butternut Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (353, 'Seattle', 'Washington', '98121', '47 Graedel Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (354, 'Nashville', 'Tennessee', '37235', '6 Dunning Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (355, 'Orlando', 'Florida', '32813', '310 Sutherland Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (356, 'Cleveland', 'Ohio', '44105', '5 Badeau Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (357, 'Monroe', 'Louisiana', '71208', '2833 Manley Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (358, 'Des Moines', 'Iowa', '50315', '132 Dovetail Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (359, 'Bethesda', 'Maryland', '20816', '10859 Mccormick Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (360, 'New Haven', 'Connecticut', '06520', '593 Schurz Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (361, 'Terre Haute', 'Indiana', '47805', '459 Quincy Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (362, 'Lakeland', 'Florida', '33811', '52 Goodland Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (363, 'Roanoke', 'Virginia', '24014', '518 Armistice Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (364, 'Tampa', 'Florida', '33673', '3722 Larry Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (365, 'Fresno', 'California', '93762', '36096 Shopko Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (366, 'Winston Salem', 'North Carolina', '27110', '98 Spenser Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (367, 'Chicago', 'Illinois', '60657', '29 Lawn Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (368, 'Kansas City', 'Missouri', '64199', '72339 Boyd Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (369, 'Canton', 'Ohio', '44720', '9 Butternut Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (370, 'Lawrenceville', 'Georgia', '30245', '350 Commercial Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (371, 'Humble', 'Texas', '77346', '64 Rutledge Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (372, 'Newton', 'Massachusetts', '02162', '44549 1st Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (373, 'El Paso', 'Texas', '88530', '28836 Northwestern Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (374, 'Inglewood', 'California', '90305', '0 Melby Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (375, 'El Paso', 'Texas', '88574', '161 Schurz Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (376, 'Salem', 'Oregon', '97312', '4370 Dixon Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (377, 'Philadelphia', 'Pennsylvania', '19104', '5652 Katie Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (378, 'Johnson City', 'Tennessee', '37605', '01234 Goodland Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (379, 'Iowa City', 'Iowa', '52245', '75 Nevada Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (380, 'San Diego', 'California', '92145', '6662 Daystar Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (381, 'Saint Paul', 'Minnesota', '55166', '423 Almo Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (382, 'Anchorage', 'Alaska', '99512', '5 Stang Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (383, 'Seattle', 'Washington', '98140', '4200 Shoshone Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (384, 'Austin', 'Texas', '78778', '3030 Jackson Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (385, 'Salt Lake City', 'Utah', '84170', '4 Vermont Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (386, 'Lynchburg', 'Virginia', '24515', '671 Warbler Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (387, 'Reading', 'Pennsylvania', '19610', '8 Fairview Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (388, 'Omaha', 'Nebraska', '68117', '5361 Dottie Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (389, 'Washington', 'District of Columbia', '20057', '569 Vera Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (390, 'Houston', 'Texas', '77015', '12745 Veith Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (391, 'Minneapolis', 'Minnesota', '55487', '08545 Kim Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (392, 'Philadelphia', 'Pennsylvania', '19120', '579 Carioca Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (393, 'Longview', 'Texas', '75605', '4 Schlimgen Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (394, 'Las Vegas', 'Nevada', '89193', '963 Lunder Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (395, 'Philadelphia', 'Pennsylvania', '19146', '56808 Bellgrove Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (396, 'Corpus Christi', 'Texas', '78475', '20111 Green Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (397, 'Worcester', 'Massachusetts', '01654', '61 Ridgeview Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (398, 'Tallahassee', 'Florida', '32309', '7 Scoville Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (399, 'Bonita Springs', 'Florida', '34135', '8294 Nova Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (400, 'Charlotte', 'North Carolina', '28225', '409 Anthes Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (401, 'Colorado Springs', 'Colorado', '80925', '1 Vernon Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (402, 'Chicago', 'Illinois', '60669', '38741 Iowa Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (403, 'Colorado Springs', 'Colorado', '80910', '9 Kensington Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (404, 'York', 'Pennsylvania', '17405', '2 Meadow Vale Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (405, 'Philadelphia', 'Pennsylvania', '19120', '88364 Transport Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (406, 'Port Washington', 'New York', '11054', '84 Jackson Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (407, 'Houston', 'Texas', '77065', '35541 Chive Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (408, 'Port Charlotte', 'Florida', '33954', '4377 Union Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (409, 'Terre Haute', 'Indiana', '47812', '281 Redwing Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (410, 'Cape Coral', 'Florida', '33915', '2439 Doe Crossing Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (411, 'Phoenix', 'Arizona', '85083', '5 Oak Valley Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (412, 'Harrisburg', 'Pennsylvania', '17105', '566 Eagle Crest Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (413, 'Topeka', 'Kansas', '66642', '002 Harbort Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (414, 'Harrisburg', 'Pennsylvania', '17105', '60129 Bultman Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (415, 'Norfolk', 'Virginia', '23504', '73880 Kings Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (416, 'North Little Rock', 'Arkansas', '72118', '654 Prairieview Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (417, 'Washington', 'District of Columbia', '20456', '78871 Hallows Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (418, 'San Jose', 'California', '95150', '00 Lillian Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (419, 'Savannah', 'Georgia', '31410', '69881 Doe Crossing Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (420, 'Dearborn', 'Michigan', '48126', '8162 Sutherland Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (421, 'Akron', 'Ohio', '44315', '1 Summerview Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (422, 'Sacramento', 'California', '94297', '85 Namekagon Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (423, 'Omaha', 'Nebraska', '68105', '1 Hagan Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (424, 'Des Moines', 'Iowa', '50315', '41077 Muir Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (425, 'New York City', 'New York', '10275', '374 Warrior Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (426, 'Delray Beach', 'Florida', '33448', '5 Lotheville Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (427, 'Columbia', 'South Carolina', '29220', '27 Dottie Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (428, 'Phoenix', 'Arizona', '85072', '877 Rigney Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (429, 'Wilmington', 'Delaware', '19805', '2 Crescent Oaks Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (430, 'Garland', 'Texas', '75044', '4434 Vernon Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (431, 'Longview', 'Texas', '75605', '07509 Lunder Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (432, 'Richmond', 'Virginia', '23260', '35 Pennsylvania Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (433, 'El Paso', 'Texas', '79934', '31 Dawn Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (434, 'Washington', 'District of Columbia', '20599', '334 Rowland Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (435, 'San Jose', 'California', '95160', '4133 Brown Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (436, 'Philadelphia', 'Pennsylvania', '19172', '862 Shelley Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (437, 'Plano', 'Texas', '75074', '858 Marquette Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (438, 'Greensboro', 'North Carolina', '27455', '1 Buell Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (439, 'Peoria', 'Illinois', '61614', '06 Maryland Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (440, 'Richmond', 'Virginia', '23208', '135 Sunnyside Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (441, 'San Francisco', 'California', '94132', '44443 Texas Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (442, 'Houston', 'Texas', '77218', '5547 Jenifer Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (443, 'Athens', 'Georgia', '30605', '057 Farmco Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (444, 'Washington', 'District of Columbia', '20580', '39838 Londonderry Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (445, 'New York City', 'New York', '10060', '767 Westerfield Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (446, 'Santa Fe', 'New Mexico', '87592', '97565 Nelson Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (447, 'Brockton', 'Massachusetts', '02405', '418 Bonner Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (448, 'Newark', 'New Jersey', '07112', '7868 Muir Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (449, 'Columbia', 'Missouri', '65211', '61 Karstens Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (450, 'Washington', 'District of Columbia', '20299', '39431 Sloan Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (451, 'Orange', 'California', '92668', '17 Laurel Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (452, 'Denver', 'Colorado', '80243', '15 Columbus Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (453, 'Seattle', 'Washington', '98166', '097 Brentwood Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (454, 'Saginaw', 'Michigan', '48604', '48315 Graedel Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (455, 'Houston', 'Texas', '77040', '273 Surrey Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (456, 'Whittier', 'California', '90605', '0698 Jenna Trail');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (457, 'Fairbanks', 'Alaska', '99790', '91 Anderson Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (458, 'Springfield', 'Missouri', '65810', '20 Namekagon Road');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (459, 'Grand Forks', 'North Dakota', '58207', '3563 Karstens Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (460, 'Baltimore', 'Maryland', '21281', '71 Bartelt Way');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (461, 'Chicago', 'Illinois', '60663', '40 Mesta Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (462, 'Lincoln', 'Nebraska', '68517', '9 Hagan Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (463, 'Jacksonville', 'Florida', '32204', '8335 Novick Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (464, 'Durham', 'North Carolina', '27710', '09344 Stephen Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (465, 'Orlando', 'Florida', '32868', '4 Susan Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (466, 'Houston', 'Texas', '77212', '173 Pearson Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (467, 'Midland', 'Texas', '79710', '7105 Lakewood Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (468, 'Cleveland', 'Ohio', '44130', '82 High Crossing Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (469, 'Salt Lake City', 'Utah', '84120', '5973 1st Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (470, 'Santa Clara', 'California', '95054', '6470 Sundown Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (471, 'Roanoke', 'Virginia', '24014', '87 Hoard Center');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (472, 'Rochester', 'Minnesota', '55905', '02920 Ronald Regan Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (473, 'Erie', 'Pennsylvania', '16565', '93 Cody Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (474, 'Tampa', 'Florida', '33686', '673 Kipling Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (475, 'Lancaster', 'Pennsylvania', '17622', '38290 Forest Run Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (476, 'Saint Louis', 'Missouri', '63121', '6 Fallview Avenue');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (477, 'San Francisco', 'California', '94105', '2 Lighthouse Bay Point');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (478, 'Saint Louis', 'Missouri', '63158', '4 Waywood Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (479, 'San Diego', 'California', '92196', '5 Hooker Terrace');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (480, 'Jefferson City', 'Missouri', '65105', '52337 Nobel Plaza');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (481, 'Carson City', 'Nevada', '89706', '08232 Fairfield Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (482, 'El Paso', 'Texas', '79994', '3602 Arapahoe Street');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (483, 'Norman', 'Oklahoma', '73071', '7303 Bonner Parkway');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (484, 'Seattle', 'Washington', '98166', '47914 Schurz Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (485, 'Miami', 'Florida', '33147', '4864 Waxwing Alley');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (486, 'Pasadena', 'California', '91186', '7637 Northland Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (487, 'Salem', 'Oregon', '97312', '9637 Brown Circle');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (488, 'Columbia', 'Missouri', '65211', '3646 Bluejay Lane');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (489, 'Dallas', 'Texas', '75323', '52 Warrior Park');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (490, 'Buffalo', 'New York', '14276', '265 John Wall Court');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (491, 'San Jose', 'California', '95138', '6184 Russell Crossing');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (492, 'Laredo', 'Texas', '78044', '6900 Main Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (493, 'New York City', 'New York', '10270', '361 Springs Pass');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (494, 'Prescott', 'Arizona', '86305', '829 Schlimgen Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (495, 'Sandy', 'Utah', '84093', '09898 Dexter Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (496, 'Washington', 'District of Columbia', '20005', '19346 Mallard Hill');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (497, 'Baltimore', 'Maryland', '21281', '5 Starling Drive');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (498, 'Colorado Springs', 'Colorado', '80940', '49563 Sutherland Junction');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (499, 'Midland', 'Texas', '79710', '487 Monument Place');
insert into public.address (user_id, city, state, zipcode, address_line_one) values (500, 'Sacramento', 'California', '95828', '0 Coolidge Trail');

SELECT setval(pg_get_serial_sequence('address', 'id'),
                        (select max(id) from "address"));